matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: stable
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    sudo: required
    language: node_js
    node_js: stable
    services:
    - docker
    - xvfb
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
    - "/^\\d+\\.\\d+\\.\\d+$/"
install:
- npm install
script: "./test/travis-build.sh"
after_success:
- tasks/arc-publish.sh
env:
  global:
  - secure: vqjLjFS1r21KkSV6g5rrnHnEDvytxFZUZGglmVBfEMWMTLmUt6tpUOZ9fQhNK02Lwoqabx+jwqkqQH3n2Qh4rdgrHciaZz8rVpB+BNRbGpk8Av9pvJEFt5P2UUfjgthgBEUCAkcMlFAWvVgGoiaZPTLufxh9YZvjilG6QrZq6907+YZmxanFfQs/YpCwhG1S36BZ5ce3FxWk7z46DETD3LIe5ThImdmxruEv31F1pNNfInoDGg1qucQiZ2Icd6e+TK6tHH76KJbWc7kaJFSaubu1zIepmUNAxwdLN13nCPcxZaTkPs+LkCel3/C0hD/GLYEc48qC6zQDiQ61/JbUqtfZqShR5qpWhG0jETwpJqlUGNeWjO8KaPUcsolDy49Iiyy+ZMN8g7qiVcxqInLM3BT0Do3vyEZA3Z3WxXDF5wGeHy8PhUbFa3wZdRxtTgNoXCPJCPAzZIPYNUbby6auhWraBHU5UfyitH+CDP34FPaM9eG9TcJbEmdoA9rB9RYEH2T6OxGN/IntSuSP1cdkN/gi4c1ZsWlZSpCS9l5emakrGa4CMl7PKUBhefvKmn/UeYi+REHR2+iNOBYGBBAzfuwSn2iLg//Cg0SdDOs557vKFozVjM2u35Qp1zoncvEZWPSL3WaVGNzmlV35yjgculysZt1tEQpLWGIBmNjEa0c=
  - secure: rBRZZG8d933qFaCaakId+GMrZFHVPHr1hJtpy/2UN8wvqvnbo9ChHGer79cfhohc23Ligx+OhdSLSVl+bC4uesVX1kUssiFUFFDcYciEsJHplO1CtvPkApsEUJL3cndrvYrA52HPOmhtpuh74Npxdn8LrPyiNnLCTdNSt86dp/w8ve2N2ZI3CSEO9nG9L+rMqEkGC5fLQxXNsD4bJoDomg9tntXQYO2anyLnHa767SkbsbfHmrrF5BRPcX8i6/ZPtqG1hOnD72rHJwN0mpLJVsL7htbs9iyMkMciQn5j+BTfV00o51Id3rR0AxrAJUPfb+62i3s7vwJh9cyOTSJ7tBQSxe5EGa0gUlikHJ3elhDFylZXQM/Tmch5yJ0btNWQTsJI7ZwWe+RImDmPtWcNijxU144VdLq8nPz7rBuV4ouIgnnLA1QUT9IjS9vR09xa0DBH2Amjoea2bj7wHj86gfb/ECMkTfRysLrs+DVysC0pqAOONuvz6mBF7OLvK7uN08w6LG3VwwHJ28K52cudiHNv1NXv9hwWxPzizg3VG6WhTlA8y/wSoNDf3Q0UROfPouwx+AM+ojpM5gYVApAwHZvAjsn/Nu+lMQVT3xfnnr+SehTJprK+9Yv1HAFMJNFKbN71w7pdUx05B/YWxMxElg6Pp8s6mlntrsFbCNJ6lCo=
  - secure: os+mH9yyl753fv3ro3mat5wzmw6BpHIOva4JFF3BtCUqZ6wIZgUyS9TwglEwpVuS1DGzzEBqwMF83azvJ63cdlLrSAkfVPtqfWxnhHQeCEN9vy1n0PBFaYOkteeng1ltHdiwSq9wNNNeiYT3cHPWhUwZM/kGelGm/AAGlQn6ZQXJp3c0g9xjnynaMpVpvRXOiBwKW4iWvIhSPDNLVJRzyGB2laZAwQFkiyA6+d3yrsMz4iJmqpicedBg1JrSe7ssIOjZ11Ypa8D875BN6hQQFCEuFr/vtEhrnettvEkmVBD83eVA9hTj5CyqlYf3nwY10kQ5VoiFuDIv67AFI+7Ty7+OSKU9TjItdXfyoGjLF+9k1NEFCDR+MvGUWLx9VV2QEw8WJ8N3ngmchk0vCqgQ/bSB1K9qCTlDiQfvGtjmnMWdG2LxewIRQlQWueYhMOvDvDEECmAYlvn32TY/w9ay3wp/uxZkJZuIDv+plE6GK+QMr3EuR/0p6RpQnpNljDbXOYHxBQ9kwbsanUoecgXjPypZkulpAPSwICMQ7SO07rJEdGZqaGquraeiERT91t+7j/2+c3I3h5YTj2IYj4EdD+0a9Dt8cO3skfw3Y4r/ThYKtK/TLpShtCQWGPGpOpGgjhTRIDb8wr612Fsc45pD+VgrtH1ZA4pr7NyApXpvJQE=
before_install:
- openssl aes-256-cbc -K $encrypted_cb8606543db7_key -iv $encrypted_cb8606543db7_iv
  -in certs.tar.enc -out certs.tar -d
- tar xvf certs.tar
